name: Build and Release CLI

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      # Node.js 및 pnpm 설정
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # 의존성 설치
      - name: Install dependencies
        run: pnpm install

      # CLI 빌드
      - name: Build CLI
        run: pnpm run build

      # 빌드 결과 아티팩트 업로드
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-build
          path: bin/ # 빌드 결과물 경로

  release:
    name: Release CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    # 빌드 작업이 성공한 후 실행
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Node.js 및 pnpm 설정
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # 빌드 아티팩트 다운로드
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-build

      # 4. NPM 배포 (semantic-release 사용)
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub 권한 토큰
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # NPM 배포 토큰
        run: pnpm run release
